# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /api
  reactive:
    # 设置浏览器session 7天过期
    session:
      cookie:
        max-age: 604800


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    default-result-set-type: default
    # 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted  #逻辑删除字段名
      logic-delete-value: 1 #逻辑已删除值
      logic-not-delete-value: 0 #逻辑未删除值
spring:
  profiles:
    active: cloud

  application:
    name: Smart-Picture-Backend


